import type { CrawledPlatform } from './shared/types';

/**
 * Coding Plan 平台初始数据
 * 数据来源：各平台官网 + coding.mcppla.net 对比
 * platform_type: 'api' = API/Token 平台, 'ide' = IDE/Agent 工具
 * accessibility: 'domestic' = 国内, 'foreign_accessible' = 国外可访问, 'foreign_blocked' = 国外无法访问
 */
export const seedPlatforms: CrawledPlatform[] = [
  // ============================================================
  //  API / Token 计费平台 (platform_type: 'api')
  // ============================================================

  // ===== 国内大厂 =====
  {
    platform: {
      name: '腾讯云',
      slug: 'tencent-cloud',
      service: 'Hy Token Plan / 通用 Token Plan',
      category: 'major',
      billing_unit: 'token',
      platform_type: 'api',
      accessibility: 'domestic',
      entry_price: 28,
      limit_desc: '3,500万 Token/月起',
      source_url: 'https://cloud.tencent.com/act/pro/tokenplan',
      last_verified: '2026-07-08T00:00:00Z',
      status: 'active',
    },
    tiers: [
      { name: 'Hy Lite', limit_short: '3,500万 Tokens', price: 28, description: '混元Hy3·约70轮问答', sort_order: 0 },
      { name: 'Hy Standard', limit_short: '1亿 Tokens', price: 78, description: '混元Hy3·约200轮问答', sort_order: 1 },
      { name: 'Hy Pro', limit_short: '3.2亿 Tokens', price: 238, description: '混元Hy3·每天高频使用', sort_order: 2 },
      { name: 'Hy Max', limit_short: '6.5亿 Tokens', price: 468, description: '混元Hy3·重度用户', sort_order: 3 },
      { name: '通用 Lite', limit_short: '3,500万 Tokens', price: 39, description: '多模型·约70轮问答', sort_order: 4 },
      { name: '通用 Standard', limit_short: '1亿 Tokens', price: 99, description: '多模型·约200轮问答', sort_order: 5 },
      { name: '通用 Pro', limit_short: '3.2亿 Tokens', price: 299, description: '多模型·每天高频使用', sort_order: 6 },
      { name: '通用 Max', limit_short: '6.5亿 Tokens', price: 599, description: '多模型·重度用户', sort_order: 7 },
    ],
    models: [
      { name: 'Claude Sonnet 4', sort_order: 0 },
      { name: 'DeepSeek-R1', sort_order: 1 },
      { name: 'DeepSeek-V3', sort_order: 2 },
      { name: 'Qwen-Max', sort_order: 3 },
      { name: 'GLM-4-Plus', sort_order: 4 },
      { name: 'Doubao-Pro', sort_order: 5 },
      { name: 'GPT-4o', sort_order: 6 },
    ],
    tools: [
      { name: '代码补全', sort_order: 0 },
      { name: '代码对话', sort_order: 1 },
    ],
    tags: [{ tag: '大厂' }, { tag: 'Token计费' }],
    rules: [
      { content: 'Token 按输入+输出合并计算', sort_order: 0 },
      { content: '不同模型消耗 Token 倍率不同', sort_order: 1 },
    ],
    remarks: [{ content: '腾讯云 Hy Token Plan，模型选择丰富' }],
  },
  {
    platform: {
      name: '阿里云百炼',
      slug: 'aliyun-bailian',
      service: '百炼 Token Plan',
      category: 'major',
      billing_unit: 'token',
      platform_type: 'api',
      accessibility: 'domestic',
      entry_price: 198,
      limit_desc: '25,000 Credits/月',
      source_url: 'https://www.aliyun.com/benefit/scene/tokenplan',
      last_verified: '2026-07-08T00:00:00Z',
      status: 'active',
    },
    tiers: [
      { name: '标准版', limit_short: '25,000 Credits/月', price: 198, description: '多模型灵活切换', sort_order: 0 },
      { name: '高级版', limit_short: '100,000 Credits/月', price: 698, description: '4倍标准版·无小时/周限额', sort_order: 1 },
      { name: '尊享版', limit_short: '250,000 Credits/月', price: 1398, description: '10倍标准版·多用户隔离', sort_order: 2 },
    ],
    models: [
      { name: 'Claude Sonnet 4', sort_order: 0 },
      { name: 'Qwen-Max', sort_order: 1 },
      { name: 'Qwen-Plus', sort_order: 2 },
      { name: 'DeepSeek-R1', sort_order: 3 },
      { name: 'DeepSeek-V3', sort_order: 4 },
      { name: 'GLM-4-Plus', sort_order: 5 },
    ],
    tools: [
      { name: '代码补全', sort_order: 0 },
      { name: '智能对话', sort_order: 1 },
    ],
    tags: [{ tag: '大厂' }, { tag: 'Token计费' }],
    rules: [
      { content: '不同模型 Token 消耗倍率不同', sort_order: 0 },
    ],
    remarks: [{ content: '阿里云百炼，支持 Claude 等国际模型' }],
  },
  {
    platform: {
      name: '百度千帆',
      slug: 'baidu-cloud',
      service: '千帆 Coding Plan',
      category: 'major',
      billing_unit: 'request_count',
      platform_type: 'api',
      accessibility: 'domestic',
      entry_price: 20,
      limit_desc: '1,200 次 · 18,000 次/月 · 首月¥20',
      source_url: 'https://cloud.baidu.com/product/codingplan.html',
      last_verified: '2026-07-08T00:00:00Z',
      status: 'active',
    },
    tiers: [
      { name: 'Coding Plan Lite', limit_short: '1,200次/5h · 18,000次/月', price: 40, description: '首月¥20·入门级开发', sort_order: 0 },
      { name: 'Coding Plan Pro', limit_short: '6,000次/5h · 90,000次/月', price: 200, description: '专业开发', sort_order: 1 },
    ],
    models: [
      { name: 'ERNIE-4.0', sort_order: 0 },
      { name: 'DeepSeek-R1', sort_order: 1 },
      { name: 'DeepSeek-V3', sort_order: 2 },
      { name: 'Qwen-Max', sort_order: 3 },
    ],
    tools: [
      { name: '代码补全', sort_order: 0 },
      { name: '代码审查', sort_order: 1 },
    ],
    tags: [{ tag: '大厂' }, { tag: '次数计费' }],
    rules: [
      { content: '每5小时独立限额', sort_order: 0 },
    ],
    remarks: [{ content: '百度千帆，Coding Plan Lite 首月¥20' }],
  },
  {
    platform: {
      name: '火山引擎',
      slug: 'volcengine',
      service: '火山方舟 Coding Plan / Agent Plan',
      category: 'major',
      billing_unit: 'request_count',
      platform_type: 'api',
      accessibility: 'domestic',
      entry_price: 9.9,
      limit_desc: '~1,200 次 · 18,000 次/月',
      source_url: 'https://www.volcengine.com/activity/codingplan',
      last_verified: '2026-07-08T00:00:00Z',
      status: 'active',
      need_rush: true,
    },
    tiers: [
      { name: 'Coding Lite', limit_short: '基础用量', price: 40, description: '限时¥9.9·已售罄', sort_order: 0 },
      { name: 'Coding Pro', limit_short: '5x Lite用量', price: 200, description: '限时¥49.9·已售罄', sort_order: 1 },
      { name: 'Agent Small', limit_short: '体验版 AFP', price: 40, description: '限时¥9.9', sort_order: 2 },
      { name: 'Agent Medium', limit_short: '5x Small AFP', price: 200, description: '限时¥49.9·含ArkClaw', sort_order: 3 },
      { name: 'Agent Large', limit_short: '12.5x Small AFP', price: 500, description: '高阶用量', sort_order: 4 },
      { name: 'Agent Max', limit_short: '25x Small AFP', price: 1000, description: '最大用量', sort_order: 5 },
    ],
    source_urls: [
      { url: 'https://www.volcengine.com/activity/codingplan', label: 'Coding Plan', sort_order: 0 },
      { url: 'https://www.volcengine.com/activity/agentplan', label: 'Agent Plan', sort_order: 1 },
    ],
    models: [
      { name: 'Doubao-Pro', sort_order: 0 },
      { name: 'Doubao-Lite', sort_order: 1 },
      { name: 'DeepSeek-R1', sort_order: 2 },
      { name: 'DeepSeek-V3', sort_order: 3 },
      { name: 'Qwen-Max', sort_order: 4 },
      { name: 'GLM-4-Plus', sort_order: 5 },
      { name: 'Claude Sonnet 4', sort_order: 6 },
      { name: 'GPT-4o', sort_order: 7 },
    ],
    tools: [
      { name: '代码补全', sort_order: 0 },
      { name: '智能对话', sort_order: 1 },
      { name: '代码解释', sort_order: 2 },
    ],
    tags: [{ tag: '大厂' }, { tag: '次数计费' }],
    rules: [
      { content: '每5小时限额独立计算', sort_order: 0 },
      { content: '不同模型消耗 AFP 数量不同', sort_order: 1 },
    ],
    remarks: [{ content: '字节跳动火山引擎，模型选择最多' }],
  },
  {
    platform: {
      name: '华为云',
      slug: 'huawei-cloud',
      service: '码道 CodeArts',
      category: 'major',
      billing_unit: 'request_count',
      platform_type: 'ide',
      accessibility: 'domestic',
      entry_price: 39,
      limit_desc: '基础版 ¥39/席位/月起',
      source_url: 'https://codearts.huaweicloud.com/pricing.html',
      last_verified: '2026-07-08T00:00:00Z',
      status: 'active',
    },
    tiers: [
      { name: '体验版', limit_short: '500万Tokens/月·50席位', price: 0, description: '免费体验', sort_order: 0 },
      { name: '基础版', limit_short: '2000万Tokens/席位/月', price: 39, description: '1-100席位', sort_order: 1 },
      { name: '专业版', limit_short: '6000万Tokens/席位/月', price: 139, description: '1-1000席位', sort_order: 2 },
    ],
    models: [
      { name: '盘古大模型', sort_order: 0 },
      { name: 'GLM-5', sort_order: 1 },
      { name: 'DeepSeek-R1', sort_order: 2 },
      { name: 'Qwen-Max', sort_order: 3 },
    ],
    tools: [
      { name: '代码补全', sort_order: 0 },
      { name: '代码生成', sort_order: 1 },
    ],
    tags: [{ tag: '大厂' }, { tag: '次数计费' }],
    rules: [
      { content: '基础版1-100席位，专业版1-1000席位', sort_order: 0 },
      { content: '体验版50席位共享500万Tokens/月', sort_order: 1 },
    ],
    remarks: [{ content: '华为云码道 CodeArts，基础版 ¥39/席位/月起' }],
  },
  {
    platform: {
      name: '讯飞星辰',
      slug: 'xfyun-spark',
      service: 'Astron Coding Plan / Token Plan',
      category: 'major',
      billing_unit: 'request_count',
      platform_type: 'api',
      accessibility: 'domestic',
      entry_price: 3.9,
      limit_desc: '请求次数不限 · 首月¥3.9',
      source_url: 'https://maas.xfyun.cn/packageSubscription?tab=month',
      last_verified: '2026-07-08T00:00:00Z',
      status: 'active',
    },
    tiers: [
      { name: 'Coding 无忧版', limit_short: '请求次数不限/月', price: 19, description: '首月¥3.9·后续¥19/月', sort_order: 0 },
      { name: 'Coding 专业版', limit_short: '~1,200次/5h · ~18,000次/月', price: 39, description: '5h约1200次·周约9000次', sort_order: 1 },
      { name: 'Coding 高效版', limit_short: '~6,000次/5h · ~90,000次/月', price: 199, description: '5h约6000次·周约45000次', sort_order: 2 },
      { name: 'Token 标准成员', limit_short: '20,000积分/月', price: 200, description: '200w tokens/月·8折¥160', sort_order: 3 },
      { name: 'Token 高级成员', limit_short: '60,000积分/月', price: 600, description: '300w tokens/月·7折¥420', sort_order: 4 },
      { name: 'Token 尊享成员', limit_short: '200,000积分/月', price: 2000, description: '500w tokens/月·6折¥1200', sort_order: 5 },
    ],
    source_urls: [
      { url: 'https://maas.xfyun.cn/packageSubscription?tab=month', label: 'Coding Plan', sort_order: 0 },
      { url: 'https://maas.xfyun.cn/tokenPlan/subscription', label: 'Token Plan', sort_order: 1 },
    ],
    models: [
      { name: 'Spark X2', sort_order: 0 },
      { name: 'Spark-X2-Flash', sort_order: 1 },
      { name: 'GLM-5.2', sort_order: 2 },
      { name: 'GLM-5.1', sort_order: 3 },
      { name: 'DeepSeek-V4-Pro', sort_order: 4 },
      { name: 'DeepSeek-V3.2', sort_order: 5 },
      { name: 'Kimi-K2.6', sort_order: 6 },
      { name: 'MiniMax-M2.5', sort_order: 7 },
      { name: 'Qwen3.5-397B', sort_order: 8 },
      { name: 'Qwen3-Coder-Next', sort_order: 9 },
    ],
    tools: [
      { name: '代码补全', sort_order: 0 },
      { name: '代码对话', sort_order: 1 },
    ],
    tags: [{ tag: '大厂' }, { tag: '次数计费' }, { tag: 'Token计费' }],
    rules: [
      { content: 'Coding Plan 5小时独立限额+周限额+月限额', sort_order: 0 },
      { content: 'Token Plan 按积分计量，不同模型消耗不同积分', sort_order: 1 },
      { content: '波谷时段(22:00-08:00/周末/节假日)积分消耗0.8倍', sort_order: 2 },
    ],
    remarks: [{ content: '讯飞星辰 MaaS，Coding 无忧版首月¥3.9，Token Plan ¥200/月起' }],
  },
  {
    platform: {
      name: '京东云',
      slug: 'jd-cloud',
      service: 'JoyBuilder Coding Plan',
      category: 'major',
      billing_unit: 'request_count',
      platform_type: 'api',
      accessibility: 'domestic',
      entry_price: 19.9,
      limit_desc: '18,000 次/月起',
      source_url: 'https://www.jdcloud.com/cn/pages/codingplan',
      last_verified: '2026-07-08T00:00:00Z',
      status: 'active',
      need_rush: true,
    },
    tiers: [
      { name: 'Coding Lite', limit_short: '18,000次/月', price: 40, description: '抢购价¥19.9·每天10:30抢购', sort_order: 0 },
      { name: 'Coding Pro', limit_short: '90,000次/月', price: 200, description: '抢购价¥99.9·5x Lite·每天10:30抢购', sort_order: 1 },
    ],
    models: [
      { name: 'DeepSeek-R1', sort_order: 0 },
      { name: 'DeepSeek-V3', sort_order: 1 },
      { name: 'Qwen-Max', sort_order: 2 },
      { name: 'ChatGLM4', sort_order: 3 },
      { name: 'Doubao-Pro', sort_order: 4 },
    ],
    tools: [
      { name: '代码补全', sort_order: 0 },
      { name: '代码对话', sort_order: 1 },
    ],
    tags: [{ tag: '大厂' }, { tag: '次数计费' }],
    rules: [],
    remarks: [{ content: '京东云 JoyBuilder' }],
  },
  {
    platform: {
      name: '小米',
      slug: 'xiaomi',
      service: 'MiMo Token Plan',
      category: 'major',
      billing_unit: 'request_count',
      platform_type: 'api',
      accessibility: 'domestic',
      entry_price: 39,
      limit_desc: '492亿积分/月起',
      source_url: 'https://platform.xiaomimimo.com/token-plan',
      last_verified: '2026-07-08T00:00:00Z',
      status: 'active',
    },
    tiers: [
      { name: 'Lite', limit_short: '492亿积分/年', price: 39, description: '尝鲜入门·年付¥411.84', sort_order: 0 },
      { name: 'Standard', limit_short: '1,320亿积分/年', price: 99, description: '进阶用户·2.7x Lite', sort_order: 1 },
      { name: 'Pro', limit_short: '4,560亿积分/年', price: 329, description: '专业开发·9.3x Lite', sort_order: 2 },
      { name: 'Max', limit_short: '9,840亿积分/年', price: 660, description: '发烧友·20x Lite', sort_order: 3 },
    ],
    models: [
      { name: 'MiMo', sort_order: 0 },
      { name: 'DeepSeek-R1', sort_order: 1 },
      { name: 'DeepSeek-V3', sort_order: 2 },
      { name: 'Qwen-Max', sort_order: 3 },
      { name: 'GLM-4-Plus', sort_order: 4 },
    ],
    tools: [
      { name: '代码补全', sort_order: 0 },
      { name: '代码对话', sort_order: 1 },
    ],
    tags: [{ tag: '大厂' }, { tag: '次数计费' }],
    rules: [],
    remarks: [{ content: '小米 MiMo Token Plan' }],
  },
  {
    platform: {
      name: '联通云',
      slug: 'unicom-cloud',
      service: '元景 Token Plan',
      category: 'major',
      billing_unit: 'token',
      platform_type: 'api',
      accessibility: 'domestic',
      entry_price: 15,
      limit_desc: '600万 Token/月起',
      source_url: 'https://www.cucloud.cn/product/tokenplan.html',
      last_verified: '2026-07-08T00:00:00Z',
      status: 'active',
    },
    tiers: [
      { name: '个人 Lite', limit_short: '600万 Tokens/月', price: 15, description: '尝鲜用户', sort_order: 0 },
      { name: '个人 Pro', limit_short: '1,200万 Tokens/月', price: 30, description: '高频开发者', sort_order: 1 },
      { name: '个人 Max', limit_short: '1,800万 Tokens/月', price: 45, description: '重度开发者', sort_order: 2 },
      { name: '团队 Lite', limit_short: '25,000 credits/月', price: 198, description: '轻度使用AI的企业团队', sort_order: 3 },
      { name: '团队 Pro', limit_short: '100,000 credits/月', price: 698, description: '高频AI编程团队', sort_order: 4 },
      { name: '团队 Max', limit_short: '250,000 credits/月', price: 1398, description: '重度依赖AI的核心团队', sort_order: 5 },
    ],
    models: [
      { name: '元景大模型', sort_order: 0 },
      { name: 'DeepSeek-V4', sort_order: 1 },
      { name: 'GLM-5', sort_order: 2 },
      { name: 'Qwen-Max', sort_order: 3 },
    ],
    tools: [
      { name: '代码补全', sort_order: 0 },
      { name: '代码对话', sort_order: 1 },
    ],
    tags: [{ tag: '大厂' }, { tag: 'Token计费' }],
    rules: [
      { content: 'Token Plan 有个人版与团队版', sort_order: 0 },
      { content: '活动期间 Token Plan Lite 免费送', sort_order: 1 },
    ],
    remarks: [{ content: '联通云元景，5档套餐可选，入门价最低' }],
  },

  // ===== 国内其他 =====
  {
    platform: {
      name: '智谱AI',
      slug: 'zhipu-ai',
      service: 'GLM Coding Plan',
      category: 'other',
      billing_unit: 'request_count',
      platform_type: 'api',
      accessibility: 'domestic',
      entry_price: 49,
      limit_desc: '基础额度 · ¥49/月起 · 团队¥598/月起',
      source_url: 'https://open.bigmodel.cn/glm-coding',
      last_verified: '2026-07-08T00:00:00Z',
      status: 'active',
      need_rush: true,
    },
    tiers: [
      { name: 'Lite', limit_short: '基础额度/月', price: 49, description: '连续包季¥44.1/月', sort_order: 0 },
      { name: 'Pro', limit_short: '5x Lite额度/月', price: 149, description: '连续包季¥134.1/月', sort_order: 1 },
      { name: 'Max', limit_short: '20x Lite额度/月', price: 469, description: '连续包季¥422.1/月', sort_order: 2 },
      { name: '团队标准版', limit_short: '0.6亿tokens/5h', price: 598, description: '年付9折¥538.2/月', sort_order: 3 },
      { name: '团队高级版', limit_short: '1.6亿tokens/5h', price: 1198, description: '年付9折¥1078.2/月', sort_order: 4 },
    ],
    models: [
      { name: 'GLM-4-Plus', sort_order: 0 },
      { name: 'GLM-4-Flash', sort_order: 1 },
      { name: 'DeepSeek-R1', sort_order: 2 },
      { name: 'Qwen-Max', sort_order: 3 },
      { name: 'Claude Sonnet 4', sort_order: 4 },
    ],
    tools: [
      { name: '代码补全', sort_order: 0 },
      { name: '代码翻译', sort_order: 1 },
    ],
    tags: [{ tag: '次数计费' }],
    rules: [
      { content: '连续包季9折，连续包年8折', sort_order: 0 },
      { content: '团队版年付9折，支持席位管理', sort_order: 1 },
    ],
    remarks: [{ content: '智谱AI GLM Coding Plan，Lite ¥49/月起' }],
  },
  {
    platform: {
      name: 'MiniMax',
      slug: 'minimax',
      service: 'MiniMax Token Plan',
      category: 'other',
      billing_unit: 'token',
      platform_type: 'api',
      accessibility: 'domestic',
      entry_price: 49,
      limit_desc: '3-4 Agent · ¥49/月起',
      source_url: 'https://platform.minimaxi.com/subscribe/token-plan?tab=individual__monthly',
      last_verified: '2026-07-08T00:00:00Z',
      status: 'active',
    },
    tiers: [
      { name: 'Plus', limit_short: '3-4个Agent用量/月', price: 49, description: '轻量个人开发', sort_order: 0 },
      { name: 'Max', limit_short: '4-5个Agent用量/月', price: 119, description: '高频编程Agent', sort_order: 1 },
      { name: 'Ultra', limit_short: '6-7个Agent用量/月', price: 469, description: '重度Agent工作流', sort_order: 2 },
    ],
    models: [
      { name: 'MiniMax-M1', sort_order: 0 },
      { name: 'abab6.5', sort_order: 1 },
      { name: 'abab6.5s', sort_order: 2 },
      { name: 'DeepSeek-R1', sort_order: 3 },
      { name: 'Qwen-Max', sort_order: 4 },
      { name: 'Claude Sonnet 4', sort_order: 5 },
      { name: 'GPT-4o', sort_order: 6 },
      { name: 'GLM-4-Plus', sort_order: 7 },
    ],
    tools: [
      { name: '代码补全', sort_order: 0 },
      { name: '代码对话', sort_order: 1 },
    ],
    tags: [{ tag: 'Token计费' }, { tag: '模型多' }],
    rules: [
      { content: '积分包按1,000积分=¥7换算，有效期365天', sort_order: 0 },
    ],
    remarks: [{ content: 'MiniMax Token Plan，Plus ¥49/月起' }],
  },
  {
    platform: {
      name: 'Kimi',
      slug: 'kimi',
      service: 'Kimi Code Plan',
      category: 'other',
      billing_unit: 'request_count',
      platform_type: 'api',
      accessibility: 'domestic',
      entry_price: 39,
      limit_desc: '基础额度 · ¥39/月起',
      source_url: 'https://kimi.com/membership/pricing',
      last_verified: '2026-07-08T00:00:00Z',
      status: 'active',
    },
    tiers: [
      { name: 'Andante', limit_short: '基础额度/月', price: 49, description: '日常使用·年付¥468/年', sort_order: 0 },
      { name: 'Moderato', limit_short: '周刷新额度/月', price: 99, description: '效率升级·年付¥948/年', sort_order: 1 },
      { name: 'Allegretto', limit_short: '充裕周限额/月', price: 199, description: '含Kimi Claw·年付¥1908/年', sort_order: 2 },
      { name: 'Allegro', limit_short: '超大额度/月', price: 699, description: '全能尊享·年付¥6708/年', sort_order: 3 },
    ],
    models: [
      { name: 'Moonshot-v1', sort_order: 0 },
      { name: 'DeepSeek-R1', sort_order: 1 },
      { name: 'Qwen-Max', sort_order: 2 },
    ],
    tools: [
      { name: '代码对话', sort_order: 0 },
      { name: '文件分析', sort_order: 1 },
    ],
    tags: [{ tag: '长上下文' }, { tag: '次数计费' }],
    rules: [
      { content: '年付享折扣，Andante年付¥39/月', sort_order: 0 },
    ],
    remarks: [{ content: 'Kimi Code Plan，Andante ¥49/月起' }],
  },
  // 百川智能: 纯按量计费无套餐，已移除
  // DeepSeek: 纯按量计费无套餐，已移除
  // 硅基流动: 纯按量计费无套餐，已移除
  // 零一万物: 纯按量计费无套餐，已移除

  {
    platform: {
      name: '商汤日日新',
      slug: 'sensenova',
      service: 'SenseNova Token Plan',
      category: 'other',
      billing_unit: 'token',
      platform_type: 'api',
      accessibility: 'domestic',
      entry_price: 0,
      limit_desc: '每模型 1,500 次/5h · 公测免费',
      source_url: 'https://www.sensenova.cn/token-plan',
      last_verified: '2026-07-08T00:00:00Z',
      status: 'active',
    },
    tiers: [
      { name: 'Free · 公测', limit_short: '每模型1,500次/5h', price: 0, description: '公测期免费，付费档即将上线', sort_order: 0 },
    ],
    models: [
      { name: 'SenseNova-6.7-Flash-Lite', sort_order: 0 },
      { name: 'SenseNova-U1-Fast', sort_order: 1 },
    ],
    tools: [
      { name: '代码对话', sort_order: 0 },
    ],
    tags: [{ tag: 'Token计费' }, { tag: '公测免费' }],
    rules: [],
    remarks: [{ content: '商汤日日新 Token Plan，公测期完全免费，付费档即将上线' }],
  },
  {
    platform: {
      name: '无问芯穹',
      slug: 'infini-ai',
      service: 'Infini Coding Plan',
      category: 'other',
      billing_unit: 'request_count',
      platform_type: 'api',
      accessibility: 'domestic',
      entry_price: 40,
      limit_desc: '1,000 次 · 12,000 次/月',
      source_url: 'https://cloud.infini-ai.com/',
      last_verified: '2026-07-08T00:00:00Z',
      status: 'offline',
    },
    tiers: [
      { name: 'Infini Plan', limit_short: '1,000次/5h · 12,000次/月', price: 40, description: null, sort_order: 0 },
    ],
    models: [
      { name: 'DeepSeek-R1', sort_order: 0 },
      { name: 'DeepSeek-V3', sort_order: 1 },
      { name: 'Qwen-Max', sort_order: 2 },
      { name: 'ChatGLM4', sort_order: 3 },
      { name: 'Doubao-Pro', sort_order: 4 },
    ],
    tools: [
      { name: '代码补全', sort_order: 0 },
      { name: '代码对话', sort_order: 1 },
    ],
    tags: [{ tag: '次数计费' }],
    rules: [],
    remarks: [{ content: '无问芯穹 Infini Coding Plan' }],
  },
  {
    platform: {
      name: '快手',
      slug: 'kuaishou',
      service: 'KwaiKAT Coding Plan',
      category: 'other',
      billing_unit: 'request_count',
      platform_type: 'api',
      accessibility: 'domestic',
      entry_price: 29,
      limit_desc: '40 Prompts/5h · ¥29/月起',
      source_url: 'https://www.streamlake.com/marketing/coding-plan',
      last_verified: '2026-07-08T00:00:00Z',
      status: 'active',
    },
    tiers: [
      { name: 'Mini', limit_short: '40 Prompts/5h', price: 29, description: 'KAT-Coder-Pro V2', sort_order: 0 },
      { name: 'Starter', limit_short: '100 Prompts/5h', price: 70, description: 'KAT-Coder-Pro V2', sort_order: 1 },
      { name: 'Pro', limit_short: '300 Prompts/5h', price: 140, description: '3x Starter', sort_order: 2 },
      { name: 'Max', limit_short: '1,000 Prompts/5h', price: 350, description: '3x+ Pro', sort_order: 3 },
    ],
    models: [
      { name: 'KAT-Coder-Pro V2', sort_order: 0 },
    ],
    tools: [
      { name: '代码对话', sort_order: 0 },
    ],
    tags: [{ tag: '次数计费' }],
    rules: [
      { content: '5小时流控，滑动步长1小时', sort_order: 0 },
    ],
    remarks: [{ content: '快手 KwaiKAT，Mini ¥29/月起' }],
  },
  {
    platform: {
      name: '摩尔线程',
      slug: 'mthreads',
      service: 'AI Coding Plan',
      category: 'other',
      billing_unit: 'request_count',
      platform_type: 'api',
      accessibility: 'domestic',
      entry_price: 0,
      limit_desc: '~40 次/5h · ¥40/月起',
      source_url: 'https://code.mthreads.com/',
      last_verified: '2026-07-08T00:00:00Z',
      status: 'active',
      need_rush: true,
    },
    tiers: [
      { name: 'Free Trial', limit_short: '~40次/5h', price: 0, description: '每日限量100名·30天有效', sort_order: 0 },
      { name: 'Lite', limit_short: '~120次/5h', price: 120, description: '¥120/季度·3x Free用量', sort_order: 1 },
      { name: 'Pro', limit_short: '~600次/5h', price: 600, description: '¥600/季度·5x Lite用量', sort_order: 2 },
      { name: 'Max', limit_short: '~2,400次/5h', price: 1200, description: '¥1,200/季度·4x Pro用量', sort_order: 3 },
    ],
    models: [
      { name: 'GLM 4.7', sort_order: 0 },
    ],
    tools: [
      { name: 'Claude Code', sort_order: 0 },
      { name: 'Cursor', sort_order: 1 },
      { name: 'OpenCode', sort_order: 2 },
      { name: 'Cline', sort_order: 3 },
      { name: 'Kilo Code', sort_order: 4 },
      { name: 'Roo Code', sort_order: 5 },
    ],
    tags: [{ tag: '次数计费' }],
    rules: [],
    remarks: [{ content: '季付制，Lite=¥40/月，Pro=¥200/月，Max=¥400/月' }, { content: '每次prompt约15-20次模型调用' }],
  },
  {
    platform: {
      name: 'UCloud 优刻得',
      slug: 'ucloud',
      service: '优云智算 Coding Plan',
      category: 'other',
      billing_unit: 'request_count',
      platform_type: 'api',
      accessibility: 'domestic',
      entry_price: 49,
      limit_desc: '~300 次 · ~1,900 次/月',
      source_url: 'https://www.compshare.cn/coding-plan',
      last_verified: '2026-07-08T00:00:00Z',
      status: 'active',
    },
    tiers: [
      { name: 'Mini 迷你版', limit_short: '~300次/5h · ~1,900次/月', price: 49, description: '覆盖主流模型', sort_order: 0 },
      { name: 'Lite 入门版', limit_short: '~600次/5h · ~3,800次/月', price: 99, description: '2x Mini', sort_order: 1 },
      { name: 'Basic 基础版', limit_short: '~1,200次/5h · ~7,600次/月', price: 199, description: '4x Mini', sort_order: 2 },
      { name: 'Pro 增强版', limit_short: '~3,000次/5h · ~19,000次/月', price: 499, description: '10x Mini', sort_order: 3 },
      { name: 'Max 高级版', limit_short: '~4,800次/5h · ~31,000次/月', price: 799, description: '16x Mini', sort_order: 4 },
      { name: 'Ultra 畅享版', limit_short: '~6,000次/5h · ~39,000次/月', price: 999, description: '20x Mini', sort_order: 5 },
    ],
    models: [
      { name: 'DeepSeek-R1', sort_order: 0 },
      { name: 'DeepSeek-V3', sort_order: 1 },
      { name: 'Qwen-Max', sort_order: 2 },
      { name: 'ChatGLM4', sort_order: 3 },
      { name: 'MiniMax-M2.7', sort_order: 4 },
      { name: 'Kimi-K2.6', sort_order: 5 },
    ],
    tools: [
      { name: '代码补全', sort_order: 0 },
      { name: '代码对话', sort_order: 1 },
    ],
    tags: [{ tag: '次数计费' }],
    rules: [
      { content: '不同模型调用倍率不同', sort_order: 0 },
    ],
    remarks: [{ content: 'UCloud 优刻得优云智算，6档套餐可选' }],
  },
  {
    platform: {
      name: 'Z.ai',
      slug: 'z-ai',
      service: 'GLM Plan (国际版)',
      category: 'other',
      billing_unit: 'request_count',
      platform_type: 'api',
      accessibility: 'foreign_accessible',
      entry_price: 122.4,
      limit_desc: 'Lite $18/月起',
      source_url: 'https://z.ai/subscribe',
      last_verified: '2026-07-08T00:00:00Z',
      status: 'active',
    },
    tiers: [
      { name: 'Lite', limit_short: '基础额度/月', price: 122.4, description: '$18/月·年付$12.6/月', sort_order: 0 },
      { name: 'Pro', limit_short: '5x Lite额度/月', price: 489.6, description: '$72/月·年付$50.4/月·含MCP', sort_order: 1 },
      { name: 'Max', limit_short: '20x Lite额度/月', price: 1088, description: '$160/月·年付$112/月·优先访问', sort_order: 2 },
    ],
    models: [
      { name: 'GLM-4-Plus', sort_order: 0 },
      { name: 'Claude Sonnet 4', sort_order: 1 },
      { name: 'GPT-4o', sort_order: 2 },
    ],
    tools: [
      { name: '代码补全', sort_order: 0 },
      { name: '代码对话', sort_order: 1 },
    ],
    tags: [{ tag: '次数计费' }],
    rules: [],
    remarks: [{ content: 'Z.ai 智谱国际版，支持 Claude/GPT' }],
  },
  {
    platform: {
      name: 'OpenCode',
      slug: 'opencode',
      service: 'OpenCode Go',
      category: 'other',
      billing_unit: 'request_count',
      platform_type: 'api',
      accessibility: 'foreign_accessible',
      entry_price: 70,
      limit_desc: '$10 用量 · $10/月',
      source_url: 'https://opencode.ai/zh/go',
      last_verified: '2026-07-08T00:00:00Z',
      status: 'active',
    },
    tiers: [
      { name: 'OpenCode Go', limit_short: '$10用量/月', price: 70, description: '按量计费·可随时取消', sort_order: 0 },
    ],
    models: [
      { name: 'Claude Sonnet 4', sort_order: 0 },
      { name: 'GPT-4o', sort_order: 1 },
      { name: 'DeepSeek-R1', sort_order: 2 },
      { name: 'Qwen-Max', sort_order: 3 },
      { name: 'GLM-4-Plus', sort_order: 4 },
    ],
    tools: [
      { name: '代码补全', sort_order: 0 },
      { name: '代码对话', sort_order: 1 },
    ],
    tags: [{ tag: '次数计费' }],
    rules: [],
    remarks: [{ content: 'OpenCode by Anomaly，模型选择丰富' }],
  },

  // OpenRouter: 纯按量计费无套餐，已移除
  // Anthropic: 纯按量计费无套餐，已移除

  // ============================================================
  //  IDE / Agent 工具 (platform_type: 'ide')
  // ============================================================

  {
    platform: {
      name: 'Cursor',
      slug: 'cursor',
      service: 'Cursor Plan',
      category: 'other',
      billing_unit: 'request_count',
      platform_type: 'ide',
      accessibility: 'foreign_accessible',
      entry_price: 135,
      limit_desc: '$20 用量/月',
      source_url: 'https://cursor.com/pricing',
      last_verified: '2026-07-08T00:00:00Z',
      status: 'active',
    },
    tiers: [
      { name: 'Hobby', limit_short: '有限Agent+Tab', price: 0, description: '免费版', sort_order: 0 },
      { name: 'Pro', limit_short: '$20用量/月', price: 135, description: '专业版 $20/月', sort_order: 1 },
      { name: 'Pro+', limit_short: 'Pro数倍用量', price: 340, description: '$50/月', sort_order: 2 },
      { name: 'Ultra', limit_short: '最大用量', price: 1360, description: '$200/月', sort_order: 3 },
    ],
    models: [
      { name: 'Claude Sonnet 4', sort_order: 0 },
      { name: 'GPT-4o', sort_order: 1 },
      { name: 'Gemini-2.5-Pro', sort_order: 2 },
    ],
    tools: [
      { name: '代码补全', sort_order: 0 },
      { name: '代码对话 (Chat)', sort_order: 1 },
      { name: 'Agent 模式', sort_order: 2 },
      { name: '终端命令', sort_order: 3 },
    ],
    tags: [{ tag: 'IDE' }, { tag: 'Agent' }],
    rules: [
      { content: 'Pro 慢速模式无限请求', sort_order: 0 },
    ],
    remarks: [{ content: 'Cursor，AI 原生 IDE，国内可访问' }],
  },
  {
    platform: {
      name: 'Windsurf',
      slug: 'windsurf',
      service: 'Windsurf Plan',
      category: 'other',
      billing_unit: 'request_count',
      platform_type: 'ide',
      accessibility: 'foreign_accessible',
      entry_price: 145,
      limit_desc: '无限 Cascade',
      source_url: 'https://windsurf.com/pricing',
      last_verified: '2026-07-08T00:00:00Z',
      status: 'active',
    },
    tiers: [
      { name: 'Free', limit_short: '轻量额度+有限模型', price: 0, description: '免费版', sort_order: 0 },
      { name: 'Pro', limit_short: '无限Cascade+全模型', price: 145, description: '专业版 $20/月', sort_order: 1 },
      { name: 'Max', limit_short: '更高额度', price: 1450, description: '$200/月', sort_order: 2 },
      { name: 'Team', limit_short: 'Pro+团队管理', price: 253, description: '$35/seat/月', sort_order: 3 },
    ],
    models: [
      { name: 'GPT-4o', sort_order: 0 },
      { name: 'Claude Sonnet 4', sort_order: 1 },
    ],
    tools: [
      { name: '代码补全', sort_order: 0 },
      { name: 'Cascade 对话', sort_order: 1 },
      { name: '终端命令', sort_order: 2 },
    ],
    tags: [{ tag: 'IDE' }, { tag: 'Agent' }],
    rules: [
      { content: 'Cascade 是 Windsurf 的核心 AI 功能', sort_order: 0 },
    ],
    remarks: [{ content: 'Windsurf (Codeium)，AI IDE' }],
  },
  {
    platform: {
      name: 'Augment Code',
      slug: 'augment-code',
      service: 'Augment Code',
      category: 'other',
      billing_unit: 'request_count',
      platform_type: 'ide',
      accessibility: 'foreign_accessible',
      entry_price: 720,
      limit_desc: 'Business $100/月 (最多50席位)',
      source_url: 'https://www.augmentcode.com/pricing',
      last_verified: '2026-07-08T00:00:00Z',
      status: 'active',
    },
    tiers: [
      { name: 'Business', limit_short: '$100用量/月 (最多50席位)', price: 720, description: '$100/月·无限席位', sort_order: 0 },
      { name: 'Enterprise', limit_short: 'Custom', price: null, description: '定制方案·SSO/SCIM', sort_order: 1 },
    ],
    models: [
      { name: 'Augment-Model', sort_order: 0 },
    ],
    tools: [
      { name: '代码补全', sort_order: 0 },
      { name: '代码对话', sort_order: 1 },
      { name: 'Agent 模式', sort_order: 2 },
    ],
    tags: [{ tag: 'IDE' }, { tag: 'Agent' }],
    rules: [],
    remarks: [{ content: 'Augment Code，专注代码理解的 AI 助手' }],
  },
  {
    platform: {
      name: 'Trae',
      slug: 'trae',
      service: 'Trae (字节跳动)',
      category: 'other',
      billing_unit: 'request_count',
      platform_type: 'ide',
      accessibility: 'domestic',
      entry_price: 22,
      limit_desc: '$3/月起',
      source_url: 'https://www.trae.ai/pricing',
      last_verified: '2026-07-08T00:00:00Z',
      status: 'active',
    },
    tiers: [
      { name: 'Free', limit_short: '有限用量+5k补全/月', price: 0, description: '免费版', sort_order: 0 },
      { name: 'Lite', limit_short: '$5用量+无限补全', price: 22, description: '$3/月', sort_order: 1 },
      { name: 'Pro', limit_short: '$20用量+无限补全', price: 72, description: '$10/月 (7天免费试用)', sort_order: 2 },
      { name: 'Pro+', limit_short: '3.5x Pro用量', price: 216, description: '$30/月', sort_order: 3 },
      { name: 'Ultra', limit_short: '20x Pro用量', price: 720, description: '$100/月', sort_order: 4 },
    ],
    models: [
      { name: 'Claude Sonnet 4', sort_order: 0 },
      { name: 'GPT-4o', sort_order: 1 },
      { name: 'Doubao-Pro', sort_order: 2 },
      { name: 'DeepSeek-R1', sort_order: 3 },
    ],
    tools: [
      { name: '代码补全', sort_order: 0 },
      { name: '代码对话 (Chat)', sort_order: 1 },
      { name: 'Agent 模式', sort_order: 2 },
    ],
    tags: [{ tag: 'IDE' }, { tag: 'Agent' }],
    rules: [],
    remarks: [{ content: 'Trae 字节跳动 AI IDE，Lite $3/月起' }],
  },
  {
    platform: {
      name: 'Qoder CN',
      slug: 'qoder-cn',
      service: 'Qoder CN (原通义灵码)',
      category: 'other',
      billing_unit: 'request_count',
      platform_type: 'ide',
      accessibility: 'domestic',
      entry_price: 59,
      limit_desc: '¥59/月起',
      source_url: 'https://qoder.com.cn/pricing',
      last_verified: '2026-07-08T00:00:00Z',
      status: 'active',
    },
    tiers: [
      { name: '体验版', limit_short: '有限体验额度', price: 0, description: '2周Pro试用+300 Credits', sort_order: 0 },
      { name: '专业版', limit_short: '2,000 Credits/月', price: 59, description: 'Pro', sort_order: 1 },
      { name: '高级版', limit_short: '6,000 Credits/月', price: 169, description: 'Pro+', sort_order: 2 },
      { name: '旗舰版', limit_short: '20,000 Credits/月', price: 559, description: '面向重度用户', sort_order: 3 },
    ],
    models: [
      { name: 'Qwen-Max', sort_order: 0 },
      { name: 'Qwen-Plus', sort_order: 1 },
    ],
    tools: [
      { name: '代码补全', sort_order: 0 },
      { name: '代码对话', sort_order: 1 },
      { name: '单元测试生成', sort_order: 2 },
      { name: '代码解释', sort_order: 3 },
    ],
    tags: [{ tag: 'IDE插件' }],
    rules: [
      { content: '体验版额度有限，适合轻度使用', sort_order: 0 },
    ],
    remarks: [{ content: 'Qoder CN (原通义灵码)，专业版 ¥59/月起' }],
  },
  // Qoder 国际版: 已恢复，定价来自 qoder.com/pricing
  {
    platform: {
      name: 'Qoder',
      slug: 'qoder',
      service: 'Qoder (International)',
      category: 'other',
      billing_unit: 'request_count',
      platform_type: 'ide',
      accessibility: 'foreign_accessible',
      entry_price: 145,
      limit_desc: 'Pro $20/月 → ¥145/月',
      source_url: 'https://qoder.com/pricing',
      last_verified: '2026-07-08T00:00:00Z',
      status: 'active',
    },
    tiers: [
      { name: 'Community', limit_short: '2-Week Trial·300 Credits', price: 0, description: 'Limited Completions·BYOK', sort_order: 0 },
      { name: 'Pro', limit_short: '2,000 Credits/月', price: 145, description: '$20/月·Extended Limits', sort_order: 1 },
      { name: 'Pro+', limit_short: '6,000 Credits/月', price: 435, description: '$60/月', sort_order: 2 },
      { name: 'Ultra', limit_short: '20,000 Credits/月', price: 1450, description: '$200/月', sort_order: 3 },
      { name: 'Teams', limit_short: '3,000 Credits/seat/月', price: 290, description: '$40/seat/月', sort_order: 4 },
      { name: 'Enterprise', limit_short: 'Custom', price: 145, description: '$20/seat/月·Credits另计', sort_order: 5 },
    ],
    models: [
      { name: 'Claude Sonnet 4', sort_order: 0 },
      { name: 'GPT-4o', sort_order: 1 },
    ],
    tools: [
      { name: '代码补全', sort_order: 0 },
      { name: '代码对话', sort_order: 1 },
      { name: 'Agent 模式', sort_order: 2 },
    ],
    tags: [{ tag: 'IDE插件' }, { tag: 'Agent' }],
    rules: [
      { content: 'Community版2周试用，300 Credits', sort_order: 0 },
    ],
    remarks: [{ content: 'Qoder International，Pro $20/月起' }],
  },
  {
    platform: {
      name: 'CodeBuddy',
      slug: 'codebuddy',
      service: 'CodeBuddy (腾讯)',
      category: 'other',
      billing_unit: 'request_count',
      platform_type: 'ide',
      accessibility: 'domestic',
      entry_price: 70,
      limit_desc: '¥70/月起 (连续包月)',
      source_url: 'https://www.codebuddy.cn/pricing/',
      last_verified: '2026-07-08T00:00:00Z',
      status: 'active',
    },
    tiers: [
      { name: '体验版', limit_short: '500积分+5k补全', price: 0, description: '免费，Auto模型调度', sort_order: 0 },
      { name: '标准版', limit_short: '2000+2000积分/月', price: 70, description: '¥70连续包月/¥99月付', sort_order: 1 },
      { name: '高级版', limit_short: '4000+5000积分/月', price: 140, description: '¥140连续包月/¥199月付', sort_order: 2 },
      { name: '旗舰版', limit_short: '20k+30k积分/月', price: 700, description: '¥700连续包月/¥999月付', sort_order: 3 },
    ],
    models: [
      { name: 'DeepSeek-R1', sort_order: 0 },
      { name: 'DeepSeek-V3', sort_order: 1 },
      { name: 'Qwen-Max', sort_order: 2 },
    ],
    tools: [
      { name: '代码补全', sort_order: 0 },
      { name: '代码对话', sort_order: 1 },
      { name: '自动任务', sort_order: 2 },
    ],
    tags: [{ tag: 'IDE插件' }],
    rules: [
      { content: '连续包月7折，年付7折，连续包年5.6折', sort_order: 0 },
    ],
    remarks: [{ content: '腾讯 CodeBuddy，标准版 ¥70/月起' }],
  },
  {
    platform: {
      name: 'GitHub Copilot',
      slug: 'github-copilot',
      service: 'GitHub Copilot',
      category: 'other',
      billing_unit: 'request_count',
      platform_type: 'ide',
      accessibility: 'foreign_accessible',
      entry_price: 70,
      limit_desc: 'Pro $10/月',
      source_url: 'https://github.com/features/copilot/plans',
      last_verified: '2026-07-08T00:00:00Z',
      status: 'active',
    },
    tiers: [
      { name: 'Free', limit_short: '2,000次补全/月', price: 0, description: '个人·基础模型', sort_order: 0 },
      { name: 'Pro', limit_short: '无限+$15 credits', price: 70, description: '个人·$10/月', sort_order: 1 },
      { name: 'Pro+', limit_short: '4x+Pro用量', price: 273, description: '个人·$39/月', sort_order: 2 },
      { name: 'Max', limit_short: '2.9x+Pro+用量', price: 700, description: '个人·$100/月', sort_order: 3 },
      { name: 'Business', limit_short: '无限补全+管理', price: 137, description: '商用·$19/seat/月', sort_order: 4 },
      { name: 'Enterprise', limit_short: '2x Business用量', price: 273, description: '商用·$39/seat/月', sort_order: 5 },
    ],
    models: [
      { name: 'GPT-4o', sort_order: 0 },
      { name: 'Claude Sonnet 4', sort_order: 1 },
      { name: 'Gemini-2.5-Pro', sort_order: 2 },
    ],
    tools: [
      { name: '代码补全', sort_order: 0 },
      { name: '代码对话 (Chat)', sort_order: 1 },
      { name: 'Agent 模式', sort_order: 2 },
      { name: '终端命令', sort_order: 3 },
    ],
    tags: [{ tag: 'IDE插件' }, { tag: 'Agent' }],
    rules: [],
    remarks: [{ content: 'GitHub Copilot，VS Code 深度集成' }],
  },
  {
    platform: {
      name: 'Claude Code',
      slug: 'claude-code',
      service: 'Claude Code (CLI)',
      category: 'other',
      billing_unit: 'request_count',
      platform_type: 'ide',
      accessibility: 'foreign_blocked',
      entry_price: 140,
      limit_desc: 'Pro $20/月起',
      source_url: 'https://claude.com/pricing',
      last_verified: '2026-07-08T00:00:00Z',
      status: 'active',
    },
    tiers: [
      { name: 'Free', limit_short: '基础用量', price: 0, description: '个人·免费版', sort_order: 0 },
      { name: 'Pro', limit_short: '标准用量', price: 140, description: '个人·$20/月(年付$16.67)', sort_order: 1 },
      { name: 'Max 5x', limit_short: '5x Pro用量', price: 700, description: '个人·$100/月起', sort_order: 2 },
      { name: 'Max 20x', limit_short: '20x Pro用量', price: 770, description: '个人·$110/月起·优先访问', sort_order: 3 },
      { name: 'Team Standard', limit_short: 'Pro级/seat', price: 158, description: '团队·$22/seat/月(年付)', sort_order: 4 },
      { name: 'Team Premium', limit_short: '5x Standard', price: 790, description: '团队·$110/seat/月(年付)', sort_order: 5 },
    ],
    models: [
      { name: 'Claude Opus 4', sort_order: 0 },
      { name: 'Claude Sonnet 4', sort_order: 1 },
    ],
    tools: [
      { name: 'Agent 模式', sort_order: 0 },
      { name: '终端命令', sort_order: 1 },
      { name: '文件操作', sort_order: 2 },
    ],
    tags: [{ tag: 'Agent' }, { tag: 'CLI' }],
    rules: [],
    remarks: [{ content: 'Claude Code，Anthropic 官方终端 Agent' }],
  },
];

/**
 * 运行初始数据导入
 * 通过 Admin API 将数据写入 D1
 */
export async function runSeed(apiBaseUrl: string, adminSecret: string): Promise<void> {
  console.log(`[Seed] Starting seed with ${seedPlatforms.length} platforms...`);
  
  const response = await fetch(`${apiBaseUrl}/api/admin/seed`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${adminSecret}`,
    },
    body: JSON.stringify({ platforms: seedPlatforms }),
  });

  if (!response.ok) {
    const error = await response.text();
    throw new Error(`Seed failed: ${error}`);
  }

  const result = await response.json() as any;
  console.log(`[Seed] Completed: ${result.results?.length || 0} platforms seeded`);
}
